### ISSUE TITLE
comparison_to_true recommends an anti-pattern.

### ISSUE THREAD

**Issue by coady** [quantifiedcode/python-anti-patterns#74]
> Comparing things to True the wrong way
> Per the PEP 8 Style Guide, the preferred ways to compare something to True are the patterns if cond is True: or if cond:.

Pep8 does _not_ recommend `if cond is True`;  it specifically says that's even worse than `== True`.  Implicit booleans are recommended.

**Comment by vogelsgesang** [comment]
I just had a quick look at PEP8, and it states:

> Yes:   if greeting:
> No:    if greeting == True:
> Worse: if greeting is True:

On the other hand, PyFlakes has error message `E712` (http://pep8.readthedocs.org/en/latest/intro.html#error-codes) with the description:

> comparison to True should be ‘if cond is True:’ or ‘if cond:’

I am not really sure what we should do in order to resolve this conflict. @acoady: What would be your resolution? Stick to the Pep8 styleguide?
@adewes: Your opinion?

**Comment by programmdesign** [comment]
I'd go with PEP8 here. If greeting. It's most concise.
Christoph

Von meinem iPhone gesendet

On 01.08.2015, at 10:20, Adrian Vogelsgesang <notifications@github.com<mailto:notifications@github.com>> wrote:


I just had a quick look at PEP8, and it states:

Yes: if greeting:
No: if greeting == True:
Worse: if greeting is True:

On the other hand, PyFlakes has error message E712 (http://pep8.readthedocs.org/en/latest/intro.html#error-codes) with the description:

comparison to True should be 'if cond is True:' or 'if cond:'

I am not really sure what we should do in order to resolve this conflict. @acoady<https://github.com/acoady>: What would be your resolution? Stick to the Pep8 styleguide?
@adewes<https://github.com/adewes>: Your opinion?

-

**Comment by vogelsgesang** [comment]
With which PEP8? Both sources are called Pep8. One is the official PEP8 styleguide, the other one is a tool which checks code against the PEP8 styleguide.

**Comment by programmdesign** [comment]
"Yes: if greeting"

**Comment by omz** [comment]
Also, what is this supposed to mean (emphasis mine)?

> The code below uses the PEP 8 preferred pattern of if cond:. **This only works if the object, variable, or expression evaluates to a Boolean value of True or False.**

I can't think of *any* expression that can't be used in a boolean context.

**Comment by tucked** [comment]
https://github.com/PyCQA/pycodestyle/issues/696
